# Generated by Django 5.0.6 on 2024-07-02 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Técnico', to='eventos.curso')),
            ],
        ),
    ]
